### PR TITLE
Adding the SEDISH MPI Enterprise Client ID to Haiti Core for testing

### PR DESCRIPTION
**Pull request by craigappl**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mogoodrich do you wanna merge this? 😊

**Comment by dkayiwa** [comment]
@craigappl do you have permission to merge this yourself? 😊

**Comment by craigappl** [comment]
@dkayiwa, I don't feel comfortable merging this because these identifiers are automatically pulled in to PIH's build process. @mogoodrich would it be better for me to make a different bundle for this identifier type to make it optional for you to install?

**Comment by mogoodrich** [comment]
Sorry @craigappl I must have missed this initial merge request, just seeing all this now... yes, probably makes sense to put this in a separate bundle and then refactor the HaitiCoreInstaller to provide utility methods for installing each bundle or set of bundles separately.

That being said, what is this identifier for?  If this is the identifier in what is intended to be the Haiti nationwide MPI, seems like it would be fine to add it to our systems in even if we aren't using it yet.

**Comment by mogoodrich** [comment]
Just following up on this and https://github.com/openmrs/openmrs-module-haiticore/pull/9

I know I recommended breaking this into a separate bundle, but I'd actually err on the side of having PIH install some identifiers that we don't use rather than split each one into it's own bundle When we do split things up hopefully we can break the bundles up by category instead of needing a unique bundle for each identifier.

Ellen is looking now to add the two identifiers mentioned in this Talk thread: https://talk.openmrs.org/t/haitian-id-numbers/13130

... and since we both want them, I'd suggest they go in a standard "HaitiPatentIdentifierType" bundle, or perhaps a "Haiti NationtionalIdentifiersBundle".

As for the other two, if the "Biometric Identifier" is something you aren't sure if you want (this is something we just "made up", I believe, for our Biometric system and is more a behind-the-scenes reference number) we can move out of Haiti Core and into our PIH Core module.

For the SEDISH MPI enterprise client ID, can you give a 1 sentence summary of it?  If the SEDISH system is meant to be a national standard, I'd say we can just put it in the main package.  If not, I'd recommend maybe making something generic like "iSante Plus Identifiers" (if this is something you are adding for iSante) and you can add other identifiers that may not be wanted by "everybody" there.

Does that make sense?  Just trying to keep things as simple as possible. Thanks!

**Comment by mogoodrich** [comment]
oops, should have @lnball  @craigappl  and @mseaton  ^^

**Comment by craigappl** [comment]
@mogoodrich,

The Enterprise Client ID is the identifier that is auto generated in our health information exchange when a person is created. It's a UUID that's assigned to each person and returned to iSantePlus. When a patient is created all of the other identifiers get pushed into separate identifier domains in the Master Person Index.

We are using the biometric identifier to store the registration ID from the M2Sys fingerprint technology already, so we want that loaded in.

I don't think we want to collect the other identifiers that Ellen proposes yet, but I do agree that we need to put them in both the Haiti Core module and the SEDISH MPI. In my mind, it makes sense to load them in to iSantéPlus in the background, but not reference them yet in the UI.

When I separated the bundles, I renamed the patientIdentifierType bundle to the biometric bundle. Let's change that back, put all of the identifiers in there and then keep the separate bundle for SEDISH MPI until you guys decide it's appropriate to add it, which doesn't have to happen anytime soon.

**Comment by mogoodrich** [comment]
Works for me... @lnball just added in the two new identifier types in a top-level bundle, so I will go ahead and move biometrics... thanks!

And yes, we have not yet enabled those two identifiers in our UI yet.

**Pull request closed without merging**
