### PR TITLE
Adding the Provider Identifier to the PersonAttributeTypes

### PR DESCRIPTION
**Pull request by craigappl**
so we can uniquely identify providers across sites.

(I'm not sure why the commits on April 25th and 28th are showing up in the PR. Please squash those commits when you merge)

### CODE REVIEW

**Comment by mogoodrich** [comment]
@craigappl what is your planned use case for this?  @mseaton  asked why we don't just use the "identiifier" column on the provider table for this, so I tried to look through the history of this attribute to find our reason for adding it but can't quite figure it out... we *do* use the "identifier" column on the provider table to store provider identifiers, and don't appear to use this attribute at all--not quite sure why we added it.  So we might just want to get rid of it--but I'd have to do a little probing first.  Thoughts on your end?

**Comment by craigappl** [comment]
Each time we push an encounter to the HIE, we need to make sure the provider ID matches what's in the health worker registry. To make this possible, we need a way to store the national provider ID in OpenMRS. I created this PR to conform to the method used in PIHCore. It sounds like there are multiple ways to solve this problem and the person attribute may not be the best. Would it be more appropriate to add a provider attribute that captures the national provider ID in the health worker registry?

**Comment by mogoodrich** [comment]
Would the "identifier" field on provider suffice, or do you need to store multiple identifiers for a single provider?

**Comment by craigappl** [comment]
@mogoodrich I think we need to have a discussion with SolDevelo, Jembi and Intrahealth on the forums. I'll close this PR and get a conversation started. Thanks to you and @mseaton for flagging this!

**Comment by mseaton** [comment]
@craigappl to answer your question above, if we do not feel like provider.identifier is the right place to store the national provider ID, then I would agree that a Provider Attribute is more appropriate than a Person Attribute for this.

**Pull request closed without merging**
